name: Generate winservice YAML
description: Generate winservice YAML

inputs:
  filename:
    description: release date
    required: true
  global-attribut-names:
    description: release date
    required: true
  global-attribut-values:
    description: release date
    required: true
  files-attribut-names:
    description: release date
    required: true
  files-attribut-values:
    description: release date
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        IFS=', ' read -r -a attribut_names <<< "${{ inputs.global-attribut-names }}"
        IFS=', ' read -r -a attribut_values <<< "${{ inputs.global-attribut-values }}"
        for i in "${attribut_names[@]}"
        do
        cat <<EOF >>${{ inputs.filename }}
        ${attribut_names[i]}: ${attribut_values[i]}
        EOF
        done

        cat ${{ inputs.filename }}
