name: Generate winservice YAML
description: Generate winservice YAML

inputs:
  filename:
    description: File name
    required: true
  global-attribut-names:
    description: Global attribut names separated by comma
    required: true
  global-attribut-values:
    description: Global attribut values separated by comma
    required: true
  files-attribut-names:
    description: Files attribut names ( files separated by comma and attribut of the same file separated by Hashtag )
    required: true
  files-attribut-values:
    description: Files attribut values ( files separated by comma and attribut of the same file separated by Hashtag )
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        IFS=',' read -r -a attribut_names <<< "${{ inputs.global-attribut-names }}"
        IFS=',' read -r -a attribut_values <<< "${{ inputs.global-attribut-values }}"
        for i in "${!attribut_names[@]}"; do
        echo "${attribut_names[i]}: ${attribut_values[i]}" >> ${{ inputs.filename }}
        done
        IFS=',' read -r -a files_attribut_names <<< "${{ inputs.files-attribut-names }}"
        IFS=',' read -r -a files_attribut_values <<< "${{ inputs.files-attribut-values }}"
        cat <<EOF >>${{ inputs.filename }}
        files:
        EOF
        for i in "${!files_attribut_names[@]}"; do
        IFS='#' read -r -a one_file_attr_names <<< "${files_attribut_names[i]}"
        IFS='#' read -r -a one_file_attr_values <<< "${files_attribut_values[i]}"
        cat <<EOF >>${{ inputs.filename }}
          - ${one_file_attr_names[0]}: ${one_file_attr_values[0]}
        EOF
        one_file_attr_names=("${one_file_attr_names[@]:1}")
        one_file_attr_values=("${one_file_attr_values[@]:1}")
        for j in "${!one_file_attr_names[@]}"; do
        cat <<EOF >>${{ inputs.filename }}
            ${one_file_attr_names[j]}: ${one_file_attr_values[j]}
        EOF
        done
        done
        cat ${{ inputs.filename }}