name: Generate winservice YAML
description: Generate winservice YAML

inputs:
  filename:
    description: release date
    required: true
  global-attribut-names:
    description: release date
    required: true
  global-attribut-values:
    description: release date
    required: true
  files-attribut-names:
    description: release date
    required: true
  files-attribut-values:
    description: release date
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        IFS=', ' read -r -a attribut_names <<< "${{ inputs.global-attribut-names }}"
        IFS=', ' read -r -a attribut_values <<< "${{ inputs.global-attribut-values }}"
        for i in "${!attribut_names[@]}"; do
        echo "${attribut_names[i]}: ${attribut_values[i]}" >> ${{ inputs.filename }}
        done
        IFS=', ' read -r -a files_attribut_names <<< "${{ inputs.files-attribut-names }}"
        IFS=', ' read -r -a files_attribut_values <<< "${{ inputs.files-attribut-values }}"
        cat <<EOF >>${{ inputs.filename }}
        files:
        EOF
        for k in "${!files_attribut_names[@]}"; do
        IFS='# ' read -r -a one_file_attr_names <<< "${files_attribut_names[k]}"
        IFS='# ' read -r -a one_file_attr_values <<< "${files_attribut_values[k]}"
        for j in "${!one_file_attr_names[@]}"; do
        echo "$j"
        if [ "$j" -eq "0" ]; then
        cat <<EOF >>${{ inputs.filename }}
          - ${one_file_attr_names[j]}: ${one_file_attr_values[j]}
        EOF
        else
        echo "else"
        cat <<EOF >>${{ inputs.filename }}
            ${one_file_attr_names[j]}: ${one_file_attr_values[j]}
        EOF
        fi
        done
        done
        cat ${{ inputs.filename }}
