name: Build, test & deploy

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:
  build_ssh:
    name: Build SSH Image
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - name: Checkout to current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event_name != 'pull_request' && github.ref || github.event.pull_request.head.sha }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Generate YAML
        uses: ./.github/actions/generate-yaml
        with:
          filename: test.yaml
          global-attribut-names: version,releaseDate
          global-attribut-values: 0.0.1,2023-01-06T00:00:00.000Z
          files-attribut-names: url#type#size#sha512,url#sha512
          files-attribut-values: https://app-desktop-releases.s3.eu-west-3.amazonaws.com/Windows+Service+0.0.1-beta+Bundler+Configuration.xml#configuration#682#cf822726ea5ab6881f7c764dd830e12a09df708f41c22b3379cd9c5b0e0a9d08d36012e297642f5903c5b5bef941e37e99a494fc2dd056e280d58ad7b1fdbffb,Outmind Setup 3.29.37-beta.exe#iF6Nat+FE/Oz6jpvE+xP1w9QzoP8ADnt6lALry1xJhGzP5Gdez9k4WPx59gGaPPTe+1EFD/99JfUhf4pBEKJ1g==
