name: Build, test & deploy

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:

  build_ssh:
    name: Build SSH Image
    runs-on: ubuntu-latest
    steps:
        # Checkout current branch
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - uses: ./.github/actions/generate-yaml
        with:
          filename: testvs.yaml
          global-attribut-names: version, releaseDate
          global-attribut-values: 0.0.1, 2023-01-06T00:00:00.000Z
          files-attribut-names: url# type# size# sha512
          files-attribut-values: https://app-desktop-releases.s3.eu-west-3.amazonaws.com/Windows+Service+0.0.1-beta+Bundler+Configuration.xml# configuration# 682# cf822726ea5ab6881f7c764dd830e12a09df708f41c22b3379cd9c5b0e0a9d08d36012e297642f5903c5b5bef941e37e99a494fc2dd056e280d58ad7b1fdbffb

