name: testing pipeline

on:
  push:
    branches:
      - "main"

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          exportEnv: false
          url: https://vault.outmind.fr
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: |
            secret/data/tnp/fleet ENROLLEMENT_TOKEN ;

